[package]
name = "cardworder"
authors = ["Aleksandr Kopytov <grender.no8@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"


[[bin]]
name = "cardworder"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[[bin]]
name = "hal_test_screen"
path = "src/bin/hal_test_screen.rs"
harness = false

[[bin]]
name = "hal_test_keyboard"
path = "src/bin/hal_test_keyboard.rs"
harness = false

[[bin]]
name = "hal_test_wifi"
path = "src/bin/hal_test_wifi.rs"
harness = false

[[bin]]
name = "hal_test_sd"
path = "src/bin/hal_test_sd.rs"
harness = false

[[bin]]
name = "hal_test_scroll"
path = "src/bin/hal_test_scroll.rs"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "s"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]

[dependencies]
# can't up esp-idf-svc to last cuz embassy does'nt support latest extenza rust toolchain
# if not need embassy - be happy to upgrade
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
esp-idf-hal = {version="0.46.2"}
esp-idf-sys = { version = "0.37.2", features = ["native", "panic_handler"] }
embedded-hal = "1.0.0"
embedded-graphics = "0.8.1"
embedded-fps = { version = "0.1.0", features = [] }
embedded-time = { version = "0.12.1", features = [] }
embedded-graphics-framebuf = "0.5.0"
u8g2-fonts = { version = "0.5.1", features = ["embedded_graphics_textstyle"] }
embedded-text = { version = "0.7.2", features = ["plugin"] }
mipidsi = "0.10"
embedded-sdmmc = { version = "0.9.0", features = ["log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postcard = { version = "1.1", features = ["alloc"] }
heapless = { version = "0.9.0", features = ["serde"] }
anyhow = "1.0.94"
log = "0.4"
rs-fsrs = { version = "1.2.1" }
fsrs-core = { path = "../fsrs-core" }

[dev-dependencies]

[build-dependencies]
embuild = { version = "0.33.0", features = ["espidf"] }

